language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

before_script:
  - (cd public && python ../serve.py) &

script:
  - $(npm bin)/cypress run --record
