language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - (cd public && python ../serve.py) &

script:
  - eslint public
  - cypress run --record --key 43e14064-ee97-42a7-b99c-be33dabe08d1
